-- 테이블형 주먼
CREATE TABLE ORDERS_BIG (
    ORDER_ID      NUMBER PRIMARY KEY,
    CUSTOMER_ID   NUMBER NOT NULL,
    ORDER_DATE    DATE NOT NULL,
    STATUS        VARCHAR2(20) NOT NULL,
    PRODUCT_CODE  VARCHAR2(20) NOT NULL,
    AMOUNT        NUMBER(10,2) NOT NULL,
    REGION        VARCHAR2(20) NOT NULL
);