CREATE TABLE DIVTBL (
    DIVISION   CHAR(4)         CONSTRAINT PK_DIVTBL PRIMARY KEY,
    NAMES      VARCHAR2(45)    CONSTRAINT NN_DIVTBL_NAMES NOT NULL
);

CREATE TABLE BOOKSTBL (
    IDX           NUMBER(38,0)     CONSTRAINT PK_BOOKSTBL PRIMARY KEY,
    AUTHOR        VARCHAR2(45)     CONSTRAINT NN_BOOKSTBL_AUTHOR NOT NULL,
    DIVISION      CHAR(4) 			CONSTRAINT FK_BOOKSTBL_DIVISION REFERENCES DIVTBL (DIVISION),
    NAMES         VARCHAR2(100)    CONSTRAINT NN_BOOKSTBL_NAMES NOT NULL,
    RELEASEDATE   DATE,
    ISBN          VARCHAR2(200)    CONSTRAINT UQ_BOOKSTBL_ISBN UNIQUE,
    PRICE         NUMBER(38,0)     CONSTRAINT CK_BOOKSTBL_PRICE CHECK (PRICE >= 0)
);

CREATE TABLE RENTALTBL (
    IDX          NUMBER(38,0) CONSTRAINT PK_RENTALTBL PRIMARY KEY,
    MEMBERIDX    NUMBER(38,0) CONSTRAINT NN_RENTALTBL_MEMBERIDX NOT NULL,
    BOOKIDX      NUMBER(38,0) CONSTRAINT NN_RENTALTBL_BOOKIDX NOT NULL,
    RENTALDATE   DATE         CONSTRAINT NN_RENTALTBL_RENTALDATE NOT NULL,
    RETURNDATE   DATE,

    CONSTRAINT FK_RENTALTBL_MEMBERIDX
        FOREIGN KEY (MEMBERIDX)
        REFERENCES MEMBERTBL (IDX),

    CONSTRAINT FK_RENTALTBL_BOOKIDX
        FOREIGN KEY (BOOKIDX)
        REFERENCES BOOKSTBL (IDX)
);