-- 전체
SELECT * FROM RENTALTBL; -- 대여일

SELECT * FROM BOOKSTBL; -- 59개 있는 거

SELECT * FROM DIVTBL; -- 분류코드(DIVISION)

SELECT * FROM MEMBERTBL; -- IDX, NAMES, LEVEL 가 있음

-- 1번 문제 현재 반납되지 않은 책의 정보 
SELECT R.IDX AS "대여번호",
       M.NAMES AS "회원명",
       B.NAMES AS "책제목",
       R.RENTALDATE AS "대여일"
FROM RENTALTBL R
JOIN MEMBERTBL M ON R.MEMBERIDX = M.IDX
JOIN BOOKSTBL B ON R.BOOKIDX = B.IDX
WHERE R.RETURNDATE IS NULL;
	

-- 2번 문제
SELECT D.DIVISION AS "분류코드",
       D.NAMES AS "분류명",
       COUNT(B.IDX) AS "도서수"
FROM DIVTBL D
LEFT JOIN BOOKSTBL B ON D.DIVISION = B.DIVISION
GROUP BY D.DIVISION, D.NAMES
ORDER BY D.DIVISION ASC;

-- 3번 문제
SELECT B.IDX AS "책번호",
       B.NAMES AS "책제목",
       COUNT(R.IDX) AS "대여횟수"
FROM BOOKSTBL B
JOIN RENTALTBL R ON B.IDX = R.BOOKIDX
GROUP BY B.IDX, B.NAMES
ORDER BY "대여횟수" DESC, B.IDX ASC;

-- 4번 문제
SELECT M.IDX AS "회원번호",
       M.NAMES AS "회원명",
       M.LEVELS AS "등급",
       COUNT(R.IDX) AS "대여횟수"
FROM MEMBERTBL M
JOIN RENTALTBL R ON M.IDX = R.MEMBERIDX
GROUP BY M.IDX, M.NAMES, M.LEVELS
HAVING COUNT(R.IDX) > 1;

-- 5번 문제
SELECT R.IDX AS "대여번호",
       M.NAMES AS "회원명",
       B.NAMES AS "책제목",
       R.RENTALDATE AS "대여일",
       R.RETURNDATE AS "반납일"
FROM RENTALTBL R
JOIN MEMBERTBL M ON R.MEMBERIDX = M.IDX
JOIN BOOKSTBL B ON R.BOOKIDX = B.IDX
WHERE R.RETURNDATE < R.RENTALDATE;
