-- 전체
SELECT * FROM EMP e;

-- 1번 답
SELECT e.EMP_NAME
	 , e.job AS "DEPT_NAME"
  FROM EMP e;

-- 2번 답
SELECT e.EMP_NAME, e.SALARY  
  FROM emp e
 WHERE e.JOB = 'DEV';
 
-- 3번 답
SELECT e.DEPT_ID
     , count(e.SALARY) AS "EMP_COUNT"
  FROM EMP e 
 GROUP BY e.DEPT_ID;

-- 4번 답
SELECT e.EMP_NAME
     , AVG(e.SALARY) AS "SALARY"
  FROM EMP e
 GROUP BY e.EMP_NAME 
HAVING avg(e.SALARY) >= 5679
 ORDER BY e.EMP_NAME ;

-- 5번 답 
SELECT P.PROJ_NAME FROM PROJECT p;